[project]
name = "resolution"
version = "0.1.0"
description = "Visualizes classical logic resolution proofs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.51.0",
]
